# Generated by Django 4.2 on 2023-04-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
