exclude: ^/frontend/|/tests/|/migrations/|tests.py
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        entry: bandit -r -c ./backend/pyproject.toml
        additional_dependencies: ["bandit[toml]"]