# Generated by Django 4.1.1 on 2022-09-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_inbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='inbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.inbox'),
        ),
    ]
