# Generated by Django 4.1.7 on 2023-03-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_room_remove_message_thread_delete_thread_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="uuid",
        ),
    ]
