name: main

on: [push, pull_request]

env:
  SECRET_KEY: test

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry
      - name: Install Dependencies
        working-directory: ./backend
        run: poetry install --no-root
      - name: Run Tests
        working-directory: ./backend
        run: poetry run pytest

