name: main

on: [push, pull_request]

env:
  SECRET_KEY: test-key
  POSTGRES_DATABASE: socmed-sample
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  REDIS_HOST: localhost

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16.1-alpine3.18
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7.2.3-alpine3.18
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install Dependencies
        working-directory: ./backend
        run: poetry config virtualenvs.create false && poetry install

      - name: Run Tests
        working-directory: ./backend
        run: poetry run pytest
