name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Environment
        run: |
          pip install --upgrade pip
          pip install pipx
          pipx ensurepath
          pipx install poetry
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          poetry install --no-root
      - name: Run Tests
        working-directory: ./backend
        run: |
          pytest .

